aws:
  s3:
    bucket_name: s3muinguard
    read_s3_url: https://s3muinguard.s3.ap-northeast-2.amazonaws.com/
    project_folder_name: app
    access_key: 123
    secret_key: 123

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstone1?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1002
    driver-class-name: com.mysql.cj.jdbc.Driver

google:
  login:
    client_id: 8687